name: Deploy to GitHub Pages

on:
    push:
        branches: [main] # Trigger deployment on push to main branch
    workflow_dispatch: # Allow manual triggering

permissions:
    contents: read
    pages: write # to deploy to Pages
    id-token: write # to verify the deployment originates from an appropriate source

concurrency:
    group: "pages" # Specifies the concurrency group
    cancel-in-progress: false # Do not cancel ongoing runs in this group

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build # Runs the build script from package.json

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload the dist directory
                  path: "./dist"

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build # Depends on the build job completing successfully
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
